% Method-of-Moments reference for the gprMax Yee-edge half-wave dipole.

clear;
close all;

script_dir = fileparts(mfilename("fullpath"));
results_dir = fullfile(script_dir, "results");
if ~isfolder(results_dir)
    mkdir(results_dir);
end

pattern_frequency = 0.95e9;
reference_impedance = 73;
wire_length = 151e-3;
wire_radius = 0.23e-3;

antenna = dipoleCylindrical( ...
    Length=wire_length, ...
    Radius=wire_radius, ...
    ClosedEnd=0 ...
);

set(groot, "defaultFigureVisible", "off");
mesh(antenna, MaxEdgeLength=5e-3);

% alpha is measured from +z in the x-z plane. The azimuth cut is measured
% conventionally around the x-y plane from +x towards +y.
alpha = (-180:2:180).';
theta = abs(alpha);
elevation = (-90:2:90).';
azimuth_columns = [0 180];

xz_grid = pattern( ...
    antenna, ...
    pattern_frequency, ...
    azimuth_columns, ...
    elevation, ...
    Type="directivity", ...
    Normalize=false ...
);
if size(xz_grid, 1) ~= numel(elevation)
    xz_grid = xz_grid.';
end
if ~isequal(size(xz_grid), [numel(elevation), numel(azimuth_columns)])
    error("Unexpected Antenna Toolbox elevation-pattern dimensions.");
end

cut_elevation = 90 - theta;
elevation_index = round((cut_elevation + 90) / 2) + 1;
xz_column = ones(size(alpha));
xz_column(alpha < 0) = 2;
xz_index = sub2ind(size(xz_grid), elevation_index, xz_column);
xz_directivity_dbi = xz_grid(xz_index);

xy_directivity_dbi = pattern( ...
    antenna, ...
    pattern_frequency, ...
    alpha, ...
    0, ...
    Type="directivity", ...
    Normalize=false ...
);
xy_directivity_dbi = reshape(xy_directivity_dbi, [], 1);
if numel(xy_directivity_dbi) ~= numel(alpha)
    error("Unexpected Antenna Toolbox azimuth-pattern dimensions.");
end

pattern_output = table( ...
    alpha, ...
    theta, ...
    cut_elevation, ...
    xz_directivity_dbi, ...
    xy_directivity_dbi, ...
    VariableNames=[ ...
        "angle_deg", ...
        "theta_deg", ...
        "elevation_deg", ...
        "xz_directivity_dbi", ...
        "xy_directivity_dbi" ...
    ] ...
);
writetable(pattern_output, fullfile(results_dir, "dipole_antenna_matlab_pattern.csv"));

% Full-sphere antenna metrics on the same non-duplicated 2 degree grid used
% by the gprMax KSIR far-field array.
full_azimuth = -180:2:178;
full_elevation = -90:2:90;
directivity_3d_dbi = orient_pattern(pattern( ...
    antenna, pattern_frequency, full_azimuth, full_elevation, ...
    Type="directivity", Normalize=false ...
), full_elevation, full_azimuth);
gain_3d_dbi = orient_pattern(pattern( ...
    antenna, pattern_frequency, full_azimuth, full_elevation, ...
    Type="gain", Normalize=false ...
), full_elevation, full_azimuth);
radiation_intensity_3d = orient_pattern(pattern( ...
    antenna, pattern_frequency, full_azimuth, full_elevation, ...
    Type="power", Normalize=false ...
), full_elevation, full_azimuth);

radiation_efficiency = efficiency(antenna, pattern_frequency);
if radiation_efficiency > 1 + 1e-6
    radiation_efficiency = radiation_efficiency / 100;
end
pattern_input_impedance = impedance(antenna, pattern_frequency);
pattern_s11 = (pattern_input_impedance - reference_impedance) / ...
    (pattern_input_impedance + reference_impedance);
mismatch_efficiency = 1 - abs(pattern_s11)^2;
total_efficiency = radiation_efficiency * mismatch_efficiency;
% The pattern API uses its fixed 50 Ohm termination for "realizedgain" and
% does not accept a custom termination for an antenna element. Apply the
% independently calculated 73 Ohm mismatch factor to the toolbox gain.
realized_gain_3d_dbi = gain_3d_dbi + 10 * log10(mismatch_efficiency);

gain_identity_error_db = max(abs( ...
    gain_3d_dbi - directivity_3d_dbi - 10 * log10(radiation_efficiency) ...
), [], "all");
realized_identity_error_db = max(abs( ...
    realized_gain_3d_dbi - gain_3d_dbi - 10 * log10(mismatch_efficiency) ...
), [], "all");
theta_axis_rad = deg2rad(0:2:180).';
power_theta_order = flipud(radiation_intensity_3d);
radiated_power_from_pattern = deg2rad(2) * sum(trapz( ...
    theta_axis_rad, ...
    power_theta_order .* sin(theta_axis_rad), ...
    1 ...
));
directivity_from_power_dbi = 10 * log10( ...
    4 * pi * radiation_intensity_3d / radiated_power_from_pattern ...
);
power_directivity_identity_error_db = max(abs( ...
    directivity_from_power_dbi - directivity_3d_dbi ...
), [], "all");

[azimuth_grid, elevation_grid] = meshgrid(full_azimuth, full_elevation);
theta_grid = 90 - elevation_grid;
phi_grid = mod(azimuth_grid, 360);
metric_output = table( ...
    theta_grid(:), ...
    phi_grid(:), ...
    directivity_3d_dbi(:), ...
    gain_3d_dbi(:), ...
    realized_gain_3d_dbi(:), ...
    radiation_intensity_3d(:), ...
    VariableNames=[ ...
        "theta_deg", ...
        "phi_deg", ...
        "directivity_dbi", ...
        "gain_dbi", ...
        "realized_gain_dbi", ...
        "radiation_intensity_w_per_sr" ...
    ] ...
);
metric_output = sortrows(metric_output, ["theta_deg", "phi_deg"]);
writetable( ...
    metric_output, ...
    fullfile(results_dir, "dipole_antenna_matlab_3d_metrics.csv") ...
);

[maximum_directivity_dbi, maximum_index] = max( ...
    directivity_3d_dbi, [], "all", "linear" ...
);
metric_summary = struct;
metric_summary.frequency_hz = pattern_frequency;
metric_summary.reference_impedance_ohm = reference_impedance;
metric_summary.radiation_efficiency = radiation_efficiency;
metric_summary.input_impedance_real_ohm = real(pattern_input_impedance);
metric_summary.input_impedance_imag_ohm = imag(pattern_input_impedance);
metric_summary.s11_magnitude_db = 20 * log10(abs(pattern_s11));
metric_summary.mismatch_efficiency = mismatch_efficiency;
metric_summary.total_efficiency = total_efficiency;
metric_summary.maximum_directivity_dbi = maximum_directivity_dbi;
metric_summary.maximum_gain_dbi = max(gain_3d_dbi, [], "all");
metric_summary.maximum_realized_gain_dbi = max( ...
    realized_gain_3d_dbi, [], "all" ...
);
metric_summary.maximum_theta_deg = theta_grid(maximum_index);
metric_summary.maximum_phi_deg = mod(azimuth_grid(maximum_index), 360);
metric_summary.gain_identity_max_error_db = gain_identity_error_db;
metric_summary.realized_gain_identity_max_error_db = realized_identity_error_db;
metric_summary.radiated_power_from_pattern_w = radiated_power_from_pattern;
metric_summary.power_directivity_identity_max_error_db = ...
    power_directivity_identity_error_db;
metric_summary.pattern_samples = height(metric_output);
metric_summary.antenna_toolbox_release = version("-release");
metrics_path = fullfile(results_dir, "dipole_antenna_matlab_3d_metrics.json");
file_id = fopen(metrics_path, "w");
if file_id < 0
    error("Could not open MATLAB metric output %s", metrics_path);
end
cleanup = onCleanup(@() fclose(file_id));
fprintf(file_id, "%s\n", jsonencode(metric_summary, PrettyPrint=true));

gprmax_s11_path = fullfile(results_dir, "dipole_antenna_gprmax_s11.csv");
if ~isfile(gprmax_s11_path)
    error( ...
        "Run dipole_antenna_gprmax.py first so the shared S11 frequency " + ...
        "grid is available at %s", ...
        gprmax_s11_path ...
    );
end
gprmax_s11 = readtable(gprmax_s11_path);
s11_frequency = gprmax_s11.frequency_hz;
input_impedance = reshape(impedance(antenna, s11_frequency), [], 1);
s11 = (input_impedance - reference_impedance) ./ ...
    (input_impedance + reference_impedance);
s11_magnitude_db = 20 * log10(abs(s11));
s11_phase_deg = rad2deg(angle(s11));

s11_output = table( ...
    s11_frequency, ...
    real(input_impedance), ...
    imag(input_impedance), ...
    real(s11), ...
    imag(s11), ...
    s11_magnitude_db, ...
    s11_phase_deg, ...
    -s11_magnitude_db, ...
    VariableNames=[ ...
        "frequency_hz", ...
        "input_impedance_real_ohm", ...
        "input_impedance_imag_ohm", ...
        "s11_real", ...
        "s11_imag", ...
        "s11_magnitude_db", ...
        "s11_phase_deg", ...
        "return_loss_db" ...
    ] ...
);
writetable(s11_output, fullfile(results_dir, "dipole_antenna_matlab_s11.csv"));

save( ...
    fullfile(results_dir, "dipole_antenna_matlab.mat"), ...
    "pattern_frequency", ...
    "reference_impedance", ...
    "wire_length", ...
    "wire_radius", ...
    "alpha", ...
    "xz_directivity_dbi", ...
    "xy_directivity_dbi", ...
    "directivity_3d_dbi", ...
    "gain_3d_dbi", ...
    "realized_gain_3d_dbi", ...
    "radiation_intensity_3d", ...
    "radiation_efficiency", ...
    "mismatch_efficiency", ...
    "total_efficiency", ...
    "s11_frequency", ...
    "input_impedance", ...
    "s11" ...
);

fprintf( ...
    "Saved MATLAB dipole patterns at %.3f GHz and S11 at %d frequencies to %s\n", ...
    pattern_frequency / 1e9, ...
    numel(s11_frequency), ...
    results_dir ...
);
fprintf("%s\n", jsonencode(metric_summary, PrettyPrint=true));


function values = orient_pattern(values, elevation, azimuth)
    if size(values, 1) ~= numel(elevation)
        values = values.';
    end
    if ~isequal(size(values), [numel(elevation), numel(azimuth)])
        error("Unexpected Antenna Toolbox pattern-array dimensions.");
    end
end
