# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  jobs:
    post_create_environment:
      - python -m pip install sphinx_rtd_theme

conda:
  environment: conda_env.yml

python:
  install:
    - requirements: docs/requirements.txt
    - method: setuptools
      path: .

sphinx:
   configuration: docs/source/conf.py


