# This file may be used to create a conda environment using:
# $ conda env create -f <this file>

name: gprMax-devel
dependencies:
- python>3.7
- colorama
- cython
- h5py
- jinja2
- jupyter
- matplotlib
- numpy
- pip
- psutil
- scipy

- pip:
  - humanize
#  - mpi4py
  - numpy-stl
#  - pycuda
#  - pyopencl
  - pybind11
  - terminaltables
  - tqdm
  - git+https://github.com/craig-warren/PyEVTK.git
