# This file may be used to create an environment using:
# $ conda create --name gprMax --file <this file>

name: gprMax
dependencies:
- python>=3.4
- cython
- h5py
- jupyter
- matplotlib
- mpi4py
- numpy
- scipy

- pip:
  - psutil
  - pyfiglet