# This file may be used to create a conda environment using:
# $ conda create --name gprMax --file <this file>

name: gprMax
dependencies:
- python>3.6
- blas=*=openblas
- colorama
- cython
- h5py
- jupyter
- matplotlib
- numpy
- psutil
- scipy

- pip:
 # - mpi4py
 # - pycuda
  - terminaltables
  - tqdm
