# This file may be used to create a conda environment using:
# $ conda env create -f <this file>

name: gprMax
dependencies:
- python>3.6
- colorama
- cython
- h5py
- jinja2
- jupyter
- matplotlib
- numpy
- pip
- psutil
- scipy
- pickle

- pip:
  - mpi4py
  - pycuda
  - pyopencl
  - terminaltables
  - tqdm
  - git+https://github.com/craig-warren/PyEVTK.git
