# This file may be used to create a conda environment using:
# $ conda env create -f <this file>

name: gprMax-devel
channels:
- conda-forge
- nodefaults
dependencies:
- python=3.12
- colorama
- cython
- h5py
- jinja2
- jupyter
- matplotlib
- meshio
- nibabel
- numpy
- pillow
- pip
- psutil
- pytest>=7
- pynrrd
- pyvista
- pythonocc-core
- scipy
- simpleitk

- pip:
  - humanize
  # MPI is optional. After creating this environment, use
  # pip install -e ".[mpi]" or pip install -e ".[mpi-fractals]".
  - numpy-stl
#  - pyobjc-framework-metal
#  - pycuda
#  - pyopencl
  - terminaltables
  - tqdm
