# Copyright (C) 2015-2026: The University of Edinburgh, United Kingdom
#
# This file is part of the gprMax source code base.
#
# gprMax is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

"""Export a series of gprMax A-scans as Sensors & Software DT1/HD files."""

from __future__ import annotations

import argparse
import math
import os
import struct
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Iterable

import numpy as np

from toolboxes.Utilities.outputfiles_trace import (
    TraceRecord,
    collect_traces,
    discover_files,
    quantity_units,
)


TRACE_HEADER_BYTES = 128
TRACE_HEADER_FORMAT = "<8f3d11f28s"
INT16_PEAK = 32_767


@dataclass(frozen=True)
class Dt1ExportSummary:
    """Metadata describing a completed DT1/HD export."""

    dt1_outputfile: Path
    hd_outputfile: Path
    trace_count: int
    sample_count: int
    sample_interval: float
    receiver: int
    component: str
    source_path: str
    time_sample_offset: float
    count_scale: float


def _output_pair(outputfile: str | Path) -> tuple[Path, Path]:
    base = Path(outputfile)
    if base.suffix.lower() in {".dt1", ".hd"}:
        base = base.with_suffix("")
    return base.with_suffix(".DT1"), base.with_suffix(".HD")


def _survey_positions(records: list[TraceRecord]) -> np.ndarray:
    positions = np.zeros(len(records), dtype=np.float64)
    for index in range(1, len(records)):
        positions[index] = positions[index - 1] + math.dist(
            records[index - 1].receiver_position,
            records[index].receiver_position,
        )
    return positions


def _quantise(records: list[TraceRecord]) -> tuple[list[np.ndarray], float]:
    peak = max(float(np.max(np.abs(record.samples), initial=0.0)) for record in records)
    scale = peak / INT16_PEAK if peak > 0 else 1.0
    quantised = [np.rint(record.samples / scale).clip(-INT16_PEAK, INT16_PEAK).astype("<i2") for record in records]
    return quantised, scale


def _trace_header(
    record: TraceRecord,
    *,
    trace_number: int,
    position: float,
    sample_count: int,
    window_ns: float,
    stacks: int,
    component: str,
) -> bytes:
    receiver = record.receiver_position
    source = record.source_position
    comment = f"gprMax {component} trace {trace_number}".encode("ascii", errors="replace")[:28].ljust(28, b"\x00")
    values = (
        float(trace_number),
        float(position),
        float(sample_count),
        float(receiver[2]),
        0.0,
        2.0,
        float(window_ns),
        float(stacks),
        float(receiver[0]),
        float(receiver[1]),
        float(receiver[2]),
        float(receiver[0]),
        float(receiver[1]),
        float(receiver[2]),
        float(source[0]),
        float(source[1]),
        float(source[2]),
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        comment,
    )
    header = struct.pack(TRACE_HEADER_FORMAT, *values)
    if len(header) != TRACE_HEADER_BYTES:
        raise AssertionError("DT1 trace header is not exactly 128 bytes")
    return header


def _hd_text(
    records: list[TraceRecord],
    *,
    positions: np.ndarray,
    dt: float,
    time_offset: float,
    component: str,
    source_path: str,
    title: str,
    count_scale: float,
    nominal_frequency_mhz: float,
    stacks: int,
) -> str:
    sample_count = records[0].samples.size
    window_ns = dt * sample_count * 1e9
    step = float(np.mean(np.diff(positions))) if len(positions) > 1 else 0.0
    separations = [math.dist(record.source_position, record.receiver_position) for record in records]
    antenna_separation = float(np.mean(separations))
    timezero_point = 1.0 - time_offset / dt
    lines = [
        "1234",
        "Data generated by gprMax",
        date.today().strftime("%Y %B %d"),
        f"NUMBER OF TRACES   = {len(records)}",
        f"NUMBER OF PTS/TRC  = {sample_count}",
        f"TIMEZERO AT POINT  = {timezero_point:.17g}",
        f"TOTAL TIME WINDOW  = {window_ns:.17g}",
        f"STARTING POSITION  = {positions[0]:.17g}",
        f"FINAL POSITION     = {positions[-1]:.17g}",
        f"STEP SIZE USED     = {step:.17g}",
        "POSITION UNITS     = m",
        f"NOMINAL FREQUENCY  = {nominal_frequency_mhz:.17g}",
        f"ANTENNA SEPARATION = {antenna_separation:.17g}",
        "PULSER VOLTAGE (V) = 0",
        f"NUMBER OF STACKS   = {stacks}",
        "SURVEY MODE        = Reflection",
        f"GPRMAX TITLE = {' '.join((title or 'UNTITLED').split())}",
        f"GPRMAX COMPONENT = {component}",
        f"GPRMAX ORIGINAL UNITS = {quantity_units(component)}",
        f"GPRMAX COUNT SCALE = {count_scale:.17g}",
        f"GPRMAX SAMPLE INTERVAL = {dt:.17g} S",
        f"GPRMAX TIME SAMPLE OFFSET = {time_offset:.17g} S",
        f"GPRMAX SOURCE PATH = {source_path}",
        "GPRMAX AMPLITUDE CONVERSION = SI_VALUE = INTEGER_COUNT * GPRMAX_COUNT_SCALE",
    ]
    return "\r\n".join(lines) + "\r\n"


def write_dt1(
    records: list[TraceRecord],
    outputfile: str | Path,
    *,
    dt: float,
    time_offset: float,
    component: str,
    receiver: int,
    source_path: str,
    title: str = "",
    nominal_frequency_mhz: float = 0.0,
    stacks: int = 1,
    overwrite: bool = False,
) -> tuple[Path, Path, float]:
    """Write validated traces as a DT1 data file and paired HD header."""

    if not records:
        raise ValueError("No traces were supplied")
    sample_count = int(records[0].samples.size)
    if sample_count < 1:
        raise ValueError("DT1 requires at least one sample per trace")
    if any(record.samples.size != sample_count for record in records):
        raise ValueError("All DT1 traces must have the same number of samples")
    if not math.isfinite(dt) or dt <= 0:
        raise ValueError("Sample interval must be finite and positive")
    if not math.isfinite(time_offset):
        raise ValueError("Sample-zero time offset must be finite")
    if not math.isfinite(nominal_frequency_mhz) or nominal_frequency_mhz < 0:
        raise ValueError("Nominal frequency must be finite and non-negative")
    if not 1 <= stacks <= 2**24:
        raise ValueError("Number of stacks must be between 1 and 2^24")

    dt1_destination, hd_destination = _output_pair(outputfile)
    existing = [path for path in (dt1_destination, hd_destination) if path.exists()]
    if existing and not overwrite:
        raise FileExistsError("DT1/HD output already exists: " + ", ".join(str(path) for path in existing))
    dt1_destination.parent.mkdir(parents=True, exist_ok=True)

    positions = _survey_positions(records)
    quantised, count_scale = _quantise(records)
    window_ns = dt * sample_count * 1e9
    hd = _hd_text(
        records,
        positions=positions,
        dt=dt,
        time_offset=time_offset,
        component=component,
        source_path=source_path,
        title=title,
        count_scale=count_scale,
        nominal_frequency_mhz=nominal_frequency_mhz,
        stacks=stacks,
    )

    dt1_temporary = dt1_destination.with_name(dt1_destination.name + ".tmp")
    hd_temporary = hd_destination.with_name(hd_destination.name + ".tmp")
    try:
        with dt1_temporary.open("wb") as stream:
            for trace_number, (record, samples, position) in enumerate(
                zip(records, quantised, positions, strict=True),
                start=1,
            ):
                stream.write(
                    _trace_header(
                        record,
                        trace_number=trace_number,
                        position=float(position),
                        sample_count=sample_count,
                        window_ns=window_ns,
                        stacks=stacks,
                        component=component,
                    )
                )
                stream.write(samples.tobytes(order="C"))
        hd_temporary.write_text(hd, encoding="ascii", newline="")
        os.replace(dt1_temporary, dt1_destination)
        os.replace(hd_temporary, hd_destination)
    finally:
        for temporary in (dt1_temporary, hd_temporary):
            if temporary.exists():
                temporary.unlink()
    return dt1_destination, hd_destination, count_scale


def export_dt1(
    outputfiles: Iterable[str | Path],
    dt1_outputfile: str | Path,
    rxnumber: int,
    rxcomponent: str,
    *,
    grid_path: str = "/",
    source_path: str | None = None,
    trace_group: str | None = None,
    nominal_frequency_mhz: float = 0.0,
    stacks: int = 1,
    overwrite: bool = False,
) -> Dt1ExportSummary:
    """Convert a series of original gprMax A-scan files into DT1/HD."""

    records, dt, time_offset, resolved_source, title = collect_traces(
        outputfiles,
        rxnumber,
        rxcomponent,
        grid_path=grid_path,
        source_path=source_path,
        trace_group=trace_group,
    )
    dt1_destination, hd_destination, count_scale = write_dt1(
        records,
        dt1_outputfile,
        dt=dt,
        time_offset=time_offset,
        component=rxcomponent,
        receiver=rxnumber,
        source_path=resolved_source,
        title=title,
        nominal_frequency_mhz=nominal_frequency_mhz,
        stacks=stacks,
        overwrite=overwrite,
    )
    return Dt1ExportSummary(
        dt1_outputfile=dt1_destination,
        hd_outputfile=hd_destination,
        trace_count=len(records),
        sample_count=records[0].samples.size,
        sample_interval=dt,
        receiver=rxnumber,
        component=rxcomponent,
        source_path=resolved_source,
        time_sample_offset=time_offset,
        count_scale=count_scale,
    )


def _default_output_name(basefilename: str, component: str) -> Path:
    base = Path(basefilename)
    if base.suffix.lower() == ".h5":
        base = base.with_suffix("")
    return base.parent / f"{base.name}_{component}"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Export a naturally ordered gprMax A-scan series as DT1/HD.",
        usage="python -m toolboxes.Utilities.outputfiles_dt1 basefilename component [options]",
    )
    parser.add_argument("basefilename", help="base name of the gprMax .h5 A-scan series")
    parser.add_argument("component", help="receiver component to export, e.g. Ez or Ey")
    parser.add_argument("-r", "--receiver", type=int, default=1, help="receiver number (default: 1)")
    parser.add_argument("-o", "--output-file", type=Path, default=None, help="destination base, .DT1, or .HD name")
    parser.add_argument("--grid", default="/", help="HDF5 grid path (default: /)")
    parser.add_argument("--source", default=None, help="source position path, e.g. srcs/src1")
    parser.add_argument("--trace-group", default=None, help="position-bearing trace group, e.g. tls/tl1")
    parser.add_argument(
        "--nominal-frequency",
        type=float,
        default=0.0,
        metavar="MHZ",
        help="nominal antenna frequency in MHz when known (default: 0, unspecified)",
    )
    parser.add_argument("--stacks", type=int, default=1, help="number of stacks recorded in HD metadata")
    parser.add_argument("--overwrite", action="store_true", help="replace an existing DT1/HD pair")
    args = parser.parse_args(argv)

    files = discover_files(args.basefilename)
    if not files:
        parser.error(f"No original A-scan files match {args.basefilename}*.h5")
    destination = args.output_file or _default_output_name(args.basefilename, args.component)
    try:
        summary = export_dt1(
            files,
            destination,
            args.receiver,
            args.component,
            grid_path=args.grid,
            source_path=args.source,
            trace_group=args.trace_group,
            nominal_frequency_mhz=args.nominal_frequency,
            stacks=args.stacks,
            overwrite=args.overwrite,
        )
    except (FileExistsError, FileNotFoundError, ValueError) as error:
        parser.error(str(error))
    print(
        f"Written {summary.trace_count} traces x {summary.sample_count} samples to "
        f"{summary.dt1_outputfile} and {summary.hd_outputfile} "
        f"(dt={summary.sample_interval:.9g} s, scale={summary.count_scale:.9g} SI/count)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
