% Method-of-Moments reference for the gprMax three-turn helix.

clear;
close all;

script_dir = fileparts(mfilename("fullpath"));
results_dir = fullfile(script_dir, "results");
if ~isfolder(results_dir)
    mkdir(results_dir);
end

pattern_frequency = 2.2e9;
reference_impedance = 150;
cylinder_radius = 1e-3;
equivalent_strip_width = 4 * cylinder_radius;

% Radius, turns, spacing and ground-plane radius retain the MATLAB default.
% The documented strip/cylinder equivalence is w = 4r. A two-millimetre
% feed stub keeps the finite-radius gprMax helix clear of its driven Yee edge.
antenna = helix( ...
    Radius=22e-3, ...
    Width=equivalent_strip_width, ...
    Turns=3, ...
    Spacing=35e-3, ...
    FeedStubHeight=2e-3, ...
    GroundPlaneRadius=75e-3, ...
    WindingDirection="CCW" ...
);

set(groot, "defaultFigureVisible", "off");
mesh(antenna, MaxEdgeLength=5e-3);

full_azimuth = -180:2:178;
full_elevation = -90:2:90;
directivity_dbi = orient_pattern(pattern( ...
    antenna, pattern_frequency, full_azimuth, full_elevation, ...
    Type="directivity", Normalize=false ...
), full_elevation, full_azimuth);
gain_dbi = orient_pattern(pattern( ...
    antenna, pattern_frequency, full_azimuth, full_elevation, ...
    Type="gain", Normalize=false ...
), full_elevation, full_azimuth);
radiation_intensity = orient_pattern(pattern( ...
    antenna, pattern_frequency, full_azimuth, full_elevation, ...
    Type="power", Normalize=false ...
), full_elevation, full_azimuth);
rhcp_directivity_dbi = orient_pattern(pattern( ...
    antenna, pattern_frequency, full_azimuth, full_elevation, ...
    Type="directivity", Polarization="RHCP", Normalize=false ...
), full_elevation, full_azimuth);
lhcp_directivity_dbi = orient_pattern(pattern( ...
    antenna, pattern_frequency, full_azimuth, full_elevation, ...
    Type="directivity", Polarization="LHCP", Normalize=false ...
), full_elevation, full_azimuth);

radiation_efficiency = efficiency(antenna, pattern_frequency);
if radiation_efficiency > 1 + 1e-6
    radiation_efficiency = radiation_efficiency / 100;
end
input_impedance = impedance(antenna, pattern_frequency);
s11 = (input_impedance - reference_impedance) / ...
    (input_impedance + reference_impedance);
mismatch_efficiency = 1 - abs(s11)^2;
total_efficiency = radiation_efficiency * mismatch_efficiency;
realized_gain_dbi = gain_dbi + 10 * log10(mismatch_efficiency);

% Recover axial ratio from the two circular components. This also produces a
% value at every common gprMax/MATLAB direction, whereas axialRatio() is used
% below as an independent check on the +z axis.
rhcp_field = sqrt(10 .^ (rhcp_directivity_dbi / 10));
lhcp_field = sqrt(10 .^ (lhcp_directivity_dbi / 10));
major_field = rhcp_field + lhcp_field;
minor_field = abs(rhcp_field - lhcp_field);
axial_ratio_db = 20 * log10(major_field ./ max(minor_field, eps));
axis_axial_ratio_native_db = axialRatio(antenna, pattern_frequency, 0, 90);

[azimuth_grid, elevation_grid] = meshgrid(full_azimuth, full_elevation);
theta_grid = 90 - elevation_grid;
phi_grid = mod(azimuth_grid, 360);
metric_output = table( ...
    theta_grid(:), ...
    phi_grid(:), ...
    directivity_dbi(:), ...
    gain_dbi(:), ...
    realized_gain_dbi(:), ...
    radiation_intensity(:), ...
    rhcp_directivity_dbi(:), ...
    lhcp_directivity_dbi(:), ...
    axial_ratio_db(:), ...
    VariableNames=[ ...
        "theta_deg", ...
        "phi_deg", ...
        "directivity_dbi", ...
        "gain_dbi", ...
        "realized_gain_dbi", ...
        "radiation_intensity_w_per_sr", ...
        "rhcp_directivity_dbi", ...
        "lhcp_directivity_dbi", ...
        "axial_ratio_db" ...
    ] ...
);
metric_output = sortrows(metric_output, ["theta_deg", "phi_deg"]);
writetable(metric_output, fullfile(results_dir, "helix_antenna_matlab_metrics.csv"));

axis_index = theta_grid == 0 & azimuth_grid == 0;
metric_summary = struct;
metric_summary.frequency_hz = pattern_frequency;
metric_summary.reference_impedance_ohm = reference_impedance;
metric_summary.cylinder_radius_m = cylinder_radius;
metric_summary.equivalent_strip_width_m = equivalent_strip_width;
metric_summary.radiation_efficiency = radiation_efficiency;
metric_summary.mismatch_efficiency = mismatch_efficiency;
metric_summary.total_efficiency = total_efficiency;
metric_summary.input_impedance_real_ohm = real(input_impedance);
metric_summary.input_impedance_imag_ohm = imag(input_impedance);
metric_summary.s11_magnitude_db = 20 * log10(abs(s11));
metric_summary.maximum_directivity_dbi = max(directivity_dbi, [], "all");
metric_summary.maximum_gain_dbi = max(gain_dbi, [], "all");
metric_summary.maximum_realized_gain_dbi = max(realized_gain_dbi, [], "all");
metric_summary.axis_directivity_dbi = directivity_dbi(axis_index);
metric_summary.axis_gain_dbi = gain_dbi(axis_index);
metric_summary.axis_realized_gain_dbi = realized_gain_dbi(axis_index);
metric_summary.axis_rhcp_directivity_dbi = rhcp_directivity_dbi(axis_index);
metric_summary.axis_lhcp_directivity_dbi = lhcp_directivity_dbi(axis_index);
metric_summary.axis_axial_ratio_from_components_db = axial_ratio_db(axis_index);
metric_summary.axis_axial_ratio_native_db = axis_axial_ratio_native_db;
metric_summary.pattern_samples = height(metric_output);
metric_summary.antenna_toolbox_release = version("-release");

json_path = fullfile(results_dir, "helix_antenna_matlab_metrics.json");
file_id = fopen(json_path, "w");
if file_id < 0
    error("Could not open MATLAB metric output %s", json_path);
end
fprintf(file_id, "%s\n", jsonencode(metric_summary, PrettyPrint=true));
fclose(file_id);

save( ...
    fullfile(results_dir, "helix_antenna_matlab.mat"), ...
    "pattern_frequency", ...
    "reference_impedance", ...
    "directivity_dbi", ...
    "gain_dbi", ...
    "realized_gain_dbi", ...
    "radiation_intensity", ...
    "rhcp_directivity_dbi", ...
    "lhcp_directivity_dbi", ...
    "axial_ratio_db", ...
    "radiation_efficiency", ...
    "mismatch_efficiency", ...
    "total_efficiency", ...
    "input_impedance", ...
    "s11" ...
);

fprintf("Saved MATLAB helix metrics to %s\n", results_dir);
fprintf("%s\n", jsonencode(metric_summary, PrettyPrint=true));


function values = orient_pattern(values, elevation, azimuth)
    if size(values, 1) ~= numel(elevation)
        values = values.';
    end
    if ~isequal(size(values), [numel(elevation), numel(azimuth)])
        error("Unexpected Antenna Toolbox pattern-array dimensions.");
    end
end
