# Copyright (C) 2015-2025: The University of Edinburgh, United Kingdom
#                 Authors: Craig Warren, Antonis Giannopoulos, John Hartley,
#                          and Nathan Mannall
#
# This file is part of gprMax.
#
# gprMax is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# gprMax is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with gprMax.  If not, see <http://www.gnu.org/licenses/>.

import re
from pathlib import Path
from typing import Generic

import h5py
import numpy as np
from mpi4py import MPI
from tqdm import tqdm

from gprMax import config
from gprMax._version import __version__
from gprMax.geometry_outputs.grid_view import GridType, GridView, MPIGridView
from gprMax.grid.fdtd_grid import FDTDGrid
from gprMax.grid.mpi_grid import MPIGrid
from gprMax.material_database import (
    create_database_document,
    make_database_id,
    material_to_database_entry,
    write_database,
)
from gprMax.materials import Material


class GeometryObject(Generic[GridType]):
    """Geometry objects to be written to file."""

    @property
    def GRID_VIEW_TYPE(self) -> type[GridView]:
        return GridView

    def __init__(
        self, grid: GridType, xs: int, ys: int, zs: int, xf: int, yf: int, zf: int, filename: str
    ):
        """
        Args:
            xs, xf, ys, yf, zs, zf: ints for extent of the volume in cells.
            filename: string for filename.
        """
        self.grid_view = self.GRID_VIEW_TYPE(grid, xs, ys, zs, xf, yf, zf)

        # Set filenames
        parts = config.sim_config.input_file_path.with_suffix("").parts
        self.filename = Path(*parts[:-1], filename)
        self.filename_hdf5 = self.filename.with_suffix(".h5")
        database_id = make_database_id(f"{self.filename.name}_materials", prefix="geometry")
        self.filename_materials = self.filename.parent / f"{database_id}.json"

        # Sizes of arrays to write necessary to update progress bar
        self.solidsize = (float)(np.prod(self.grid_view.size) * np.dtype(np.uint32).itemsize)
        self.rigidsize = (float)(18 * np.prod(self.grid_view.size) * np.dtype(np.int8).itemsize)
        self.IDsize = (float)(6 * np.prod(self.grid_view.size + 1) * np.dtype(np.uint32).itemsize)
        self.datawritesize = self.solidsize + self.rigidsize + self.IDsize

    @property
    def grid(self) -> GridType:
        return self.grid_view.grid

    def write_metadata(self, file_handler: h5py.File, title: str):
        file_handler.attrs["gprMax"] = __version__
        file_handler.attrs["Title"] = title
        file_handler.attrs["dx_dy_dz"] = (self.grid.dx, self.grid.dy, self.grid.dz)

    @staticmethod
    def _material_keys(materials):
        """Generate unique schema-safe keys while retaining original IDs."""

        keys = []
        for index, material in enumerate(materials):
            slug = re.sub(r"[^A-Za-z0-9_.-]+", "_", material.ID).strip("_.-") or "material"
            if not slug[0].isalpha():
                slug = f"m_{slug}"
            keys.append(f"material_{index:03d}_{slug}")
        return keys

    def _material_document(self, keys):
        database_id = self.filename_materials.stem
        entries = {}
        for key, material in zip(keys, self.grid_view.materials):
            entry = dict(material_to_database_entry(material))
            metadata = dict(entry.get("metadata", {}))
            metadata["original_id"] = material.ID
            provenance = getattr(material, "database_provenance", None)
            if provenance is not None:
                metadata["source_database"] = provenance
            entry["metadata"] = metadata
            entries[key] = entry
        return create_database_document(
            database_id,
            entries,
            name=f"Materials for geometry object {self.filename_hdf5.name}",
            description="Generated by #geometry_objects_write; material keys match /material_keys in the HDF5 file.",
        )

    def write_hdf5(self, title: str, pbar: tqdm):
        """Writes a geometry objects file in HDF5 format.

        Args:
            G: FDTDGrid class describing a grid in a model.
            pbar: Progress bar class instance.
        """

        self.grid_view.initialise_materials()

        ID = self.grid_view.get_ID()
        data = self.grid_view.get_solid().astype(np.int16)
        rigidE = self.grid_view.get_rigidE()
        rigidH = self.grid_view.get_rigidH()

        ID = self.grid_view.map_to_view_materials(ID)
        data = self.grid_view.map_to_view_materials(data)
        material_keys = self._material_keys(self.grid_view.materials)

        with h5py.File(self.filename_hdf5, "w") as fdata:
            self.write_metadata(fdata, title)

            fdata["/data"] = data
            pbar.update(self.solidsize)

            fdata["/rigidE"] = rigidE
            fdata["/rigidH"] = rigidH
            pbar.update(self.rigidsize)

            fdata["/ID"] = ID
            pbar.update(self.IDsize)

            fdata.create_dataset("/material_keys", data=np.asarray(material_keys, dtype="S"))
            fdata.attrs["MaterialDatabase"] = self.filename_materials.stem
            fdata.attrs["MaterialDatabaseSchemaVersion"] = 1

        write_database(self.filename_materials, self._material_document(material_keys))


class MPIGeometryObject(GeometryObject[MPIGrid]):
    @property
    def GRID_VIEW_TYPE(self) -> type[MPIGridView]:
        return MPIGridView

    def _merge_negative_rigid_halos(
        self, output: np.ndarray, grid_array: np.ndarray, tag_base: int
    ) -> np.ndarray:
        """Merge rigid flags built in a neighbour's negative cell halo.

        Geometry primitives are built independently on every MPI rank. An
        object exactly on an internal rank face can therefore set one of the
        redundant rigid markers in the upper rank's negative halo, while the
        corresponding cell is written to HDF5 by the lower rank. Component
        IDs already have node ownership rules; cell-based rigid arrays need
        this one-plane maximum reduction before their non-overlapping write.
        """
        for dimension in range(3):
            negative, positive = self.grid_view.comm.Shift(dimension, 1)
            send_plane = None
            if negative != MPI.PROC_NULL:
                spatial = [self.grid_view.getter_slice(axis) for axis in range(3)]
                start = self.grid_view.start[dimension] - self.grid_view.step[dimension]
                spatial[dimension] = slice(start, start + 1)
                send_plane = np.ascontiguousarray(grid_array[(..., *spatial)])

            received = self.grid_view.comm.sendrecv(
                sendobj=send_plane,
                dest=negative,
                sendtag=tag_base + dimension,
                source=positive,
                recvtag=tag_base + dimension,
            )
            if received is not None:
                target = [slice(None)] * output.ndim
                target[output.ndim - 3 + dimension] = slice(-1, None)
                np.maximum(output[tuple(target)], received, out=output[tuple(target)])

        return output

    def write_hdf5(self, title: str, pbar: tqdm):
        """Writes a geometry objects file in HDF5 format.

        Args:
            G: FDTDGrid class describing a grid in a model.
            pbar: Progress bar class instance.
        """
        assert isinstance(self.grid_view, self.GRID_VIEW_TYPE)

        self.grid_view.initialise_materials()

        ID = self.grid_view.get_ID()
        data = self.grid_view.get_solid().astype(np.int16)
        rigidE = self.grid_view.get_rigidE()
        rigidH = self.grid_view.get_rigidH()

        rigidE = self._merge_negative_rigid_halos(rigidE, self.grid.rigidE, 4100)
        rigidH = self._merge_negative_rigid_halos(rigidH, self.grid.rigidH, 4200)

        ID = self.grid_view.map_to_view_materials(ID)
        data = self.grid_view.map_to_view_materials(data)
        material_keys = self._material_keys(self.grid_view.materials)

        with h5py.File(self.filename_hdf5, "w", driver="mpio", comm=self.grid_view.comm) as fdata:
            self.write_metadata(fdata, title)

            dset_slice = self.grid_view.get_3d_output_slice()

            dset = fdata.create_dataset("/data", self.grid_view.global_size, dtype=data.dtype)
            dset[dset_slice] = data
            pbar.update(self.solidsize)

            rigid_E_dataset = fdata.create_dataset(
                "/rigidE", (12, *self.grid_view.global_size), dtype=rigidE.dtype
            )
            rigid_E_dataset[:, dset_slice[0], dset_slice[1], dset_slice[2]] = rigidE

            rigid_H_dataset = fdata.create_dataset(
                "/rigidH", (6, *self.grid_view.global_size), dtype=rigidH.dtype
            )
            rigid_H_dataset[:, dset_slice[0], dset_slice[1], dset_slice[2]] = rigidH
            pbar.update(self.rigidsize)

            dset_slice = self.grid_view.get_3d_output_slice(upper_bound_exclusive=False)

            dset = fdata.create_dataset(
                "/ID", (6, *(self.grid_view.global_size + 1)), dtype=ID.dtype
            )
            dset[:, dset_slice[0], dset_slice[1], dset_slice[2]] = ID
            pbar.update(self.IDsize)

            fdata.create_dataset("/material_keys", data=np.asarray(material_keys, dtype="S"))
            fdata.attrs["MaterialDatabase"] = self.filename_materials.stem
            fdata.attrs["MaterialDatabaseSchemaVersion"] = 1

        # Every rank has the same compact material catalogue after
        # initialise_materials(); only rank zero writes the companion JSON.
        if self.grid_view.materials is not None:
            if self.grid_view.comm.rank == 0:
                write_database(self.filename_materials, self._material_document(material_keys))
