% Reference Method-of-Moments solution for the rectangular patch case in
% the MathWorks "Patch Antenna with Dielectric Substrate" example.

clear;
close all;

script_dir = fileparts(mfilename("fullpath"));
results_dir = fullfile(script_dir, "results");
if ~isfolder(results_dir)
    mkdir(results_dir);
end

frequency = 2.37e9;
reference_impedance = 50;

patch = patchMicrostrip;
patch.Length = 40e-3;
patch.Width = 30e-3;
patch.Height = 1.57e-3;
patch.GroundPlaneLength = 80e-3;
patch.GroundPlaneWidth = 60e-3;
patch.FeedOffset = [5.5e-3 0];
patch.Substrate = dielectric(Name="material1", EpsilonR=2.33, LossTangent=0);

antenna = pcbStack(patch);
antenna.FeedDiameter = sqrt(2) * 1e-3;
antenna.FeedViaModel = "square";

% These are the mesh limits used by the official MathWorks example.
set(groot, "defaultFigureVisible", "off");
mesh(antenna, MaxEdgeLength=0.01, MinEdgeLength=0.003);

% alpha is a signed principal-plane angle measured from +z. Positive
% angles turn towards +x in the x-z plane and +y in the y-z plane.
alpha = (-180:2:180).';
theta = abs(alpha);
elevation = (-90:2:90).';
azimuth = [0 180 90 -90];

directivity_grid = pattern( ...
    antenna, frequency, azimuth, elevation, Type="directivity", Normalize=false ...
);
if size(directivity_grid, 1) ~= numel(elevation)
    directivity_grid = directivity_grid.';
end
if ~isequal(size(directivity_grid), [numel(elevation), numel(azimuth)])
    error("Unexpected Antenna Toolbox pattern-array dimensions.");
end

cut_elevation = 90 - theta;
elevation_index = round((cut_elevation + 90) / 2) + 1;
xz_column = ones(size(alpha));
xz_column(alpha < 0) = 2;
yz_column = 3 * ones(size(alpha));
yz_column(alpha < 0) = 4;

row_index = elevation_index;
xz_index = sub2ind(size(directivity_grid), row_index, xz_column);
yz_index = sub2ind(size(directivity_grid), row_index, yz_column);
xz_directivity_dbi = directivity_grid(xz_index);
yz_directivity_dbi = directivity_grid(yz_index);

output = table( ...
    alpha, ...
    theta, ...
    cut_elevation, ...
    xz_directivity_dbi, ...
    yz_directivity_dbi, ...
    VariableNames=[ ...
        "angle_deg", ...
        "theta_deg", ...
        "elevation_deg", ...
        "xz_directivity_dbi", ...
        "yz_directivity_dbi" ...
    ] ...
);
writetable(output, fullfile(results_dir, "patch_antenna_matlab_pattern.csv"));

% Evaluate the one-port MoM impedance on the exact positive-frequency bins
% retained by the gprMax engineering-FFT post-processor. Calculating S11 from
% impedance avoids imposing an RF Toolbox dependency on this comparison.
gprmax_s11_path = fullfile(results_dir, "patch_antenna_gprmax_s11.csv");
if ~isfile(gprmax_s11_path)
    error( ...
        "Run patch_antenna_gprmax.py before MATLAB so the shared S11 " + ...
        "frequency grid is available at %s", ...
        gprmax_s11_path ...
    );
end
gprmax_s11 = readtable(gprmax_s11_path);
s11_frequency = gprmax_s11.frequency_hz;
input_impedance = reshape(impedance(antenna, s11_frequency), [], 1);
s11 = (input_impedance - reference_impedance) ./ ...
    (input_impedance + reference_impedance);
s11_magnitude_db = 20 * log10(abs(s11));
s11_phase_deg = rad2deg(angle(s11));
return_loss_db = -s11_magnitude_db;

s11_output = table( ...
    s11_frequency, ...
    real(input_impedance), ...
    imag(input_impedance), ...
    real(s11), ...
    imag(s11), ...
    s11_magnitude_db, ...
    s11_phase_deg, ...
    return_loss_db, ...
    VariableNames=[ ...
        "frequency_hz", ...
        "input_impedance_real_ohm", ...
        "input_impedance_imag_ohm", ...
        "s11_real", ...
        "s11_imag", ...
        "s11_magnitude_db", ...
        "s11_phase_deg", ...
        "return_loss_db" ...
    ] ...
);
writetable(s11_output, fullfile(results_dir, "patch_antenna_matlab_s11.csv"));
save( ...
    fullfile(results_dir, "patch_antenna_matlab_pattern.mat"), ...
    "frequency", ...
    "reference_impedance", ...
    "alpha", ...
    "theta", ...
    "xz_directivity_dbi", ...
    "yz_directivity_dbi", ...
    "s11_frequency", ...
    "input_impedance", ...
    "s11" ...
);

fprintf( ...
    "Saved MATLAB patch patterns at %.3f GHz to %s\n", ...
    frequency / 1e9, ...
    results_dir ...
);
fprintf( ...
    "Saved MATLAB patch impedance and S11 at %d frequencies to %s\n", ...
    numel(s11_frequency), ...
    results_dir ...
);
