% Independent Antenna Toolbox comparison with the gprMax antenna metrics.

clear;
close all;

script_dir = fileparts(mfilename("fullpath"));
results_dir = fullfile(script_dir, "results");
if ~isfolder(results_dir)
    mkdir(results_dir);
end

frequency = 2.37e9;
reference_impedance = 50;
angular_step = 2;

patch = patchMicrostrip;
patch.Length = 40e-3;
patch.Width = 30e-3;
patch.Height = 1.57e-3;
patch.GroundPlaneLength = 80e-3;
patch.GroundPlaneWidth = 60e-3;
patch.FeedOffset = [5.5e-3 0];
patch.Substrate = dielectric(Name="material1", EpsilonR=2.33, LossTangent=0);

antenna = pcbStack(patch);
antenna.FeedDiameter = sqrt(2) * 1e-3;
antenna.FeedViaModel = "square";
set(groot, "defaultFigureVisible", "off");
mesh(antenna, MaxEdgeLength=0.01, MinEdgeLength=0.003);

% MATLAB uses azimuth/elevation; gprMax uses polar theta/azimuth phi.
% Excluding +180 avoids duplicating the periodic azimuth endpoint.
azimuth = -180:angular_step:(180 - angular_step);
elevation = -90:angular_step:90;
directivity_dbi = orient_pattern(pattern( ...
    antenna, frequency, azimuth, elevation, ...
    Type="directivity", Normalize=false ...
), elevation, azimuth);
gain_dbi = orient_pattern(pattern( ...
    antenna, frequency, azimuth, elevation, ...
    Type="gain", Normalize=false ...
), elevation, azimuth);
realized_gain_dbi = orient_pattern(pattern( ...
    antenna, frequency, azimuth, elevation, ...
    Type="realizedgain", Normalize=false ...
), elevation, azimuth);
radiation_intensity = orient_pattern(pattern( ...
    antenna, frequency, azimuth, elevation, ...
    Type="power", Normalize=false ...
), elevation, azimuth);

radiation_efficiency_raw = efficiency(antenna, frequency);
% Antenna Toolbox currently returns efficiency as a fraction. Retain the
% raw result in the metadata and tolerate a percentage-valued older release.
radiation_efficiency = radiation_efficiency_raw;
if radiation_efficiency > 1 + 1e-6
    radiation_efficiency = radiation_efficiency / 100;
end
input_impedance = impedance(antenna, frequency);
s11 = (input_impedance - reference_impedance) / ...
    (input_impedance + reference_impedance);
mismatch_efficiency = 1 - abs(s11)^2;
total_efficiency = radiation_efficiency * mismatch_efficiency;

% These residuals independently check the interpretation of the three
% Antenna Toolbox pattern types used in the cross-code comparison.
gain_identity_error_db = max(abs( ...
    gain_dbi - directivity_dbi - 10 * log10(radiation_efficiency) ...
), [], "all");
realized_identity_error_db = max(abs( ...
    realized_gain_dbi - gain_dbi - 10 * log10(mismatch_efficiency) ...
), [], "all");

% Numerically integrate the independently returned linear power pattern.
% The azimuth endpoint is periodic and deliberately omitted, while theta
% includes both zero-weight poles and is integrated by the trapezoidal rule.
theta_axis_rad = deg2rad(0:angular_step:180).';
power_theta_order = flipud(radiation_intensity);
radiated_power_from_pattern = deg2rad(angular_step) * sum(trapz( ...
    theta_axis_rad, ...
    power_theta_order .* sin(theta_axis_rad), ...
    1 ...
));
directivity_from_power_dbi = 10 * log10( ...
    4 * pi * radiation_intensity / radiated_power_from_pattern ...
);
power_directivity_identity_error_db = max(abs( ...
    directivity_from_power_dbi - directivity_dbi ...
), [], "all");

[azimuth_grid, elevation_grid] = meshgrid(azimuth, elevation);
theta_grid = 90 - elevation_grid;
phi_grid = mod(azimuth_grid, 360);
angular_data = table( ...
    theta_grid(:), ...
    phi_grid(:), ...
    directivity_dbi(:), ...
    gain_dbi(:), ...
    realized_gain_dbi(:), ...
    radiation_intensity(:), ...
    VariableNames=[ ...
        "theta_deg", ...
        "phi_deg", ...
        "directivity_dbi", ...
        "gain_dbi", ...
        "realized_gain_dbi", ...
        "radiation_intensity_w_per_sr" ...
    ] ...
);
angular_data = sortrows(angular_data, ["theta_deg", "phi_deg"]);
writetable( ...
    angular_data, ...
    fullfile(results_dir, "patch_antenna_matlab_3d_metrics.csv") ...
);

[maximum_directivity_dbi, maximum_directivity_index] = max( ...
    directivity_dbi, [], "all", "linear" ...
);
[maximum_gain_dbi, maximum_gain_index] = max(gain_dbi, [], "all", "linear");
[maximum_realized_gain_dbi, maximum_realized_index] = max( ...
    realized_gain_dbi, [], "all", "linear" ...
);

metrics = struct;
metrics.frequency_hz = frequency;
metrics.reference_impedance_ohm = reference_impedance;
metrics.angular_step_deg = angular_step;
metrics.radiation_efficiency_raw = radiation_efficiency_raw;
metrics.radiation_efficiency = radiation_efficiency;
metrics.input_impedance_real_ohm = real(input_impedance);
metrics.input_impedance_imag_ohm = imag(input_impedance);
metrics.s11_real = real(s11);
metrics.s11_imag = imag(s11);
metrics.s11_magnitude_db = 20 * log10(abs(s11));
metrics.mismatch_efficiency = mismatch_efficiency;
metrics.total_efficiency = total_efficiency;
metrics.maximum_directivity_dbi = maximum_directivity_dbi;
metrics.maximum_gain_dbi = maximum_gain_dbi;
metrics.maximum_realized_gain_dbi = maximum_realized_gain_dbi;
metrics.maximum_directivity_theta_deg = theta_grid(maximum_directivity_index);
metrics.maximum_directivity_phi_deg = mod( ...
    azimuth_grid(maximum_directivity_index), 360 ...
);
metrics.maximum_gain_theta_deg = theta_grid(maximum_gain_index);
metrics.maximum_gain_phi_deg = mod(azimuth_grid(maximum_gain_index), 360);
metrics.maximum_realized_gain_theta_deg = theta_grid(maximum_realized_index);
metrics.maximum_realized_gain_phi_deg = mod( ...
    azimuth_grid(maximum_realized_index), 360 ...
);
metrics.gain_identity_max_error_db = gain_identity_error_db;
metrics.realized_gain_identity_max_error_db = realized_identity_error_db;
metrics.radiated_power_from_pattern_w = radiated_power_from_pattern;
metrics.power_directivity_identity_max_error_db = ...
    power_directivity_identity_error_db;
metrics.pattern_samples = height(angular_data);
metrics.antenna_toolbox_release = version("-release");

metrics_path = fullfile(results_dir, "patch_antenna_matlab_3d_metrics.json");
file_id = fopen(metrics_path, "w");
if file_id < 0
    error("Could not open MATLAB metric output %s", metrics_path);
end
cleanup = onCleanup(@() fclose(file_id));
fprintf(file_id, "%s\n", jsonencode(metrics, PrettyPrint=true));

save( ...
    fullfile(results_dir, "patch_antenna_matlab_3d_metrics.mat"), ...
    "frequency", ...
    "reference_impedance", ...
    "azimuth", ...
    "elevation", ...
    "directivity_dbi", ...
    "gain_dbi", ...
    "realized_gain_dbi", ...
    "radiation_intensity", ...
    "radiation_efficiency", ...
    "input_impedance", ...
    "s11", ...
    "mismatch_efficiency", ...
    "total_efficiency" ...
);

fprintf("%s\n", jsonencode(metrics, PrettyPrint=true));
fprintf("Saved MATLAB full-sphere antenna metrics to %s\n", results_dir);


function values = orient_pattern(values, elevation, azimuth)
    if size(values, 1) ~= numel(elevation)
        values = values.';
    end
    if ~isequal(size(values), [numel(elevation), numel(azimuth)])
        error("Unexpected Antenna Toolbox pattern-array dimensions.");
    end
end
