% MATLAB Antenna Toolbox references for strip dipoles above terminal PEC.

clear;
close all;

script_dir = fileparts(mfilename("fullpath"));
results_dir = fullfile(script_dir, "results");
if ~isfolder(results_dir)
    mkdir(results_dir);
end

pattern_frequency = 1e9;
reference_impedance = 50;
s11_frequency = (0.5e9:0.05e9:1.5e9).';
% The exactly grazing direction is excluded because the terminal-PEC
% layered Green function is defined only in the open upper half-space.
theta = (0:1:89).';
far_radius = 100;

dipole_element = dipole( ...
    Length=0.150, ...
    Width=0.015, ...
    Tilt=90, ...
    TiltAxis=[0 1 0] ...
);

cases = struct([]);
cases(1).name = "lambda_8";
cases(1).antenna = reflector( ...
    Exciter=dipole_element, ...
    GroundPlaneLength=inf, ...
    GroundPlaneWidth=inf, ...
    Spacing=0.0375 ...
);
cases(2).name = "lambda_4";
cases(2).antenna = reflector( ...
    Exciter=dipole_element, ...
    GroundPlaneLength=inf, ...
    GroundPlaneWidth=inf, ...
    Spacing=0.075 ...
);

set(groot, "defaultFigureVisible", "off");
summary = struct;
for case_index = 1:numel(cases)
    name = cases(case_index).name;
    antenna = cases(case_index).antenna;

    for plane_index = 1:2
        if plane_index == 1
            plane = "e_plane";
            phi = 0;
        else
            plane = "h_plane";
            phi = 90;
        end
        elevation = 90 - theta;
        directivity_dbi = pattern( ...
            antenna, pattern_frequency, phi, elevation, ...
            Type="directivity", Normalize=false ...
        );
        directivity_dbi = reshape(directivity_dbi, [], 1);

        theta_rad = deg2rad(theta);
        phi_rad = deg2rad(phi);
        points = far_radius * [ ...
            sin(theta_rad).' * cos(phi_rad); ...
            sin(theta_rad).' * sin(phi_rad); ...
            cos(theta_rad).' ...
        ];
        [electric, ~] = EHfields(antenna, pattern_frequency, points);
        etheta_unit = [ ...
            cos(theta_rad).' * cos(phi_rad); ...
            cos(theta_rad).' * sin(phi_rad); ...
            -sin(theta_rad).' ...
        ];
        ephi_unit = repmat([-sin(phi_rad); cos(phi_rad); 0], 1, numel(theta));
        etheta = sum(electric .* etheta_unit, 1).';
        ephi = sum(electric .* ephi_unit, 1).';

        output = table( ...
            theta, ...
            directivity_dbi, ...
            real(etheta), ...
            imag(etheta), ...
            real(ephi), ...
            imag(ephi), ...
            VariableNames=[ ...
                "theta_deg", ...
                "directivity_dbi", ...
                "Etheta_real", ...
                "Etheta_imag", ...
                "Ephi_real", ...
                "Ephi_imag" ...
            ] ...
        );
        writetable( ...
            output, ...
            fullfile(results_dir, "reflector_dipole_matlab_" + name + "_" + plane + ".csv") ...
        );
    end

    azimuth = -180:2:178;
    elevation = 0:2:90;
    directivity_3d = orient_pattern(pattern( ...
        antenna, pattern_frequency, azimuth, elevation, ...
        Type="directivity", Normalize=false ...
    ), elevation, azimuth);
    gain_3d = orient_pattern(pattern( ...
        antenna, pattern_frequency, azimuth, elevation, ...
        Type="gain", Normalize=false ...
    ), elevation, azimuth);
    radiation_efficiency = efficiency(antenna, pattern_frequency);
    if radiation_efficiency > 1 + 1e-6
        radiation_efficiency = radiation_efficiency / 100;
    end

    input_impedance = reshape(impedance(antenna, s11_frequency), [], 1);
    s11 = (input_impedance - reference_impedance) ./ ...
        (input_impedance + reference_impedance);
    port_output = table( ...
        s11_frequency, ...
        real(input_impedance), ...
        imag(input_impedance), ...
        real(s11), ...
        imag(s11), ...
        20 * log10(abs(s11)), ...
        rad2deg(angle(s11)), ...
        VariableNames=[ ...
            "frequency_hz", ...
            "Zin_real_ohm", ...
            "Zin_imag_ohm", ...
            "S11_real", ...
            "S11_imag", ...
            "S11_magnitude_db", ...
            "S11_phase_deg" ...
        ] ...
    );
    writetable( ...
        port_output, ...
        fullfile(results_dir, "reflector_dipole_matlab_" + name + "_port.csv") ...
    );

    [maximum_directivity, maximum_index] = max(directivity_3d, [], "all", "linear");
    [elevation_grid, azimuth_grid] = ndgrid(elevation, azimuth);
    pattern_index = find(s11_frequency == pattern_frequency, 1);
    mismatch_efficiency = 1 - abs(s11(pattern_index))^2;
    item = struct;
    item.maximum_directivity_dbi = maximum_directivity;
    item.maximum_directivity_theta_deg = 90 - elevation_grid(maximum_index);
    item.maximum_directivity_phi_deg = mod(azimuth_grid(maximum_index), 360);
    item.maximum_gain_dbi = max(gain_3d, [], "all");
    item.maximum_realized_gain_dbi = max(gain_3d, [], "all") + ...
        10 * log10(mismatch_efficiency);
    item.radiation_efficiency = radiation_efficiency;
    item.total_efficiency = radiation_efficiency * mismatch_efficiency;
    item.input_impedance_real_ohm = real(input_impedance(pattern_index));
    item.input_impedance_imag_ohm = imag(input_impedance(pattern_index));
    item.s11_magnitude_db = 20 * log10(abs(s11(pattern_index)));
    item.s11_phase_deg = rad2deg(angle(s11(pattern_index)));
    summary.(name) = item;
end

report = struct;
report.matlab_release = version("-release");
report.pattern_frequency_hz = pattern_frequency;
report.reference_impedance_ohm = reference_impedance;
report.far_field_sampling_radius_metres = far_radius;
report.cases = summary;
file_id = fopen(fullfile(results_dir, "reflector_dipole_matlab_summary.json"), "w");
if file_id < 0
    error("Could not create MATLAB summary JSON");
end
cleanup = onCleanup(@() fclose(file_id));
fprintf(file_id, "%s\n", jsonencode(report, PrettyPrint=true));
save(fullfile(results_dir, "reflector_dipole_matlab.mat"), "cases", "report");

function values = orient_pattern(values, elevation, azimuth)
    if size(values, 1) == numel(elevation) && size(values, 2) == numel(azimuth)
        return;
    end
    if size(values, 2) == numel(elevation) && size(values, 1) == numel(azimuth)
        values = values.';
        return;
    end
    error("Unexpected Antenna Toolbox pattern-array dimensions.");
end
