import argparse
import json
import logging
import re
from pathlib import Path

import h5py
import numpy as np

from gprMax.material_database import create_database_document, make_database_id, write_database

from .convert import convert_files

logger = logging.getLogger(__name__)


def _write_or_preserve_database(database_file, database_id, material_keys, entries):
    """Create a material template without overwriting user-supplied values."""

    if database_file.exists():
        try:
            existing = json.loads(database_file.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise ValueError(
                f"Existing material database {database_file} is invalid JSON: {exc.msg}"
            ) from exc
        recorded_id = existing.get("database", {}).get("id")
        recorded_materials = existing.get("materials")
        if recorded_id != database_id or not isinstance(recorded_materials, dict):
            raise ValueError(
                f"Existing material database {database_file} is not the companion database "
                "for this conversion"
            )
        if list(recorded_materials) != material_keys:
            raise ValueError(
                f"Existing material database {database_file} has material keys that do not "
                "match the STL inputs; move it aside before converting the changed geometry"
            )
        logger.info(f"Preserved existing editable material database: {database_file}")
        return

    write_database(
        database_file,
        create_database_document(
            database_id,
            entries,
            name="STLtoVoxel material assignments",
            description=(
                "Template generated by STLtoVoxel. Replace null constitutive values before use."
            ),
        ),
    )
    logger.info(f"Written editable material database: {database_file}")


def main():
    logging.basicConfig(format="%(message)s", level=logging.INFO)

    # Parse command line arguments
    parser = argparse.ArgumentParser(
        description="Allows the user to convert a STL files to voxelized mesh.",
        usage="python -m toolboxes.STLtoVoxel.stltovoxel stlfilename -dxdydz VALUE",
    )
    parser.add_argument(
        "stlfiles",
        help="can be the filename of a single STL file, or the path to folder containing multiple STL files",
    )
    parser.add_argument(
        "-dxdydz",
        type=float,
        required=True,
        help="discretisation to use in voxelisation process",
    )
    args = parser.parse_args()

    input_path = Path(args.stlfiles)
    if input_path.is_dir():
        files = sorted(input_path.glob("*.stl"))
        filename_hdf5 = input_path / f"{input_path.name}_geo.h5"
    elif input_path.is_file():
        files = [input_path]
        filename_hdf5 = input_path.with_name(f"{input_path.stem}_geo.h5")
    else:
        parser.error(f"STL file or directory does not exist: {input_path}")

    if not files:
        parser.error(f"No STL files found in: {input_path}")

    dxdydz = (args.dxdydz, args.dxdydz, args.dxdydz)

    newline = "\n\t"
    logger.info(f"\nConverting STL file(s): {newline.join(map(str, files))}")
    model_array = convert_files(files, dxdydz)
    logger.info(
        f"Number of voxels: {model_array.shape[0]} x {model_array.shape[1]} x {model_array.shape[2]}"
    )
    logger.info(f"Spatial discretisation: {dxdydz[0]} x {dxdydz[1]} x {dxdydz[2]}m")

    # Write HDF5 file for gprMax using voxels
    material_keys = []
    for index, path in enumerate(files):
        slug = re.sub(r"[^A-Za-z0-9_.-]+", "_", path.stem).strip("_.-") or "material"
        material_keys.append(f"material_{index:03d}_{slug}")
    database_id = make_database_id(f"{filename_hdf5.stem}_materials", prefix="geometry")
    database_file = filename_hdf5.with_name(f"{database_id}.json")
    with h5py.File(filename_hdf5, "w") as f:
        f.create_dataset("data", data=model_array)
        f.create_dataset("material_keys", data=np.asarray(material_keys, dtype="S"))
        f.attrs["dx_dy_dz"] = (dxdydz[0], dxdydz[1], dxdydz[2])
        f.attrs["MaterialDatabase"] = database_id
        f.attrs["MaterialDatabaseSchemaVersion"] = 1
    logger.info(f"Written geometry object file: {filename_hdf5}")

    # Do not silently invent properties for CAD/STL solids. The null values
    # make this an editable template and produce a clear validation error if
    # it is used before the constitutive parameters are filled in.
    entries = {}
    for key, path in zip(material_keys, files):
        entries[key] = {
            "name": path.stem,
            "model": "constant",
            "base": {
                "relative_permittivity": None,
                "electric_conductivity_s_per_m": None,
                "relative_permeability": None,
                "magnetic_conductivity_s_per_m": None,
            },
            "metadata": {
                "original_id": path.stem,
                "source_stl": str(path),
            },
        }
    _write_or_preserve_database(
        database_file,
        database_id,
        material_keys,
        entries,
    )


if __name__ == "__main__":
    main()
