% MoM reference for the equal-phase two-element gprMax dipole array.

clear;
close all;

script_dir = fileparts(mfilename("fullpath"));
results_dir = fullfile(script_dir, "results");
if ~isfolder(results_dir)
    mkdir(results_dir);
end

element_length = 75e-3;
element_spacing = 80e-3;
wire_radius = 0.23e-3;
pattern_frequency = 1.9e9;
reference_impedance = 50;

element = dipoleCylindrical( ...
    Length=element_length, ...
    Radius=wire_radius ...
);
antenna = linearArray( ...
    Element=element, ...
    NumElements=2, ...
    ElementSpacing=element_spacing, ...
    AmplitudeTaper=[1 1], ...
    PhaseShift=0 ...
);

set(groot, "defaultFigureVisible", "off");
mesh(antenna, MaxEdgeLength=5e-3);

alpha = (-180:2:180).';
theta = abs(alpha);
elevation = (-90:2:90).';
cut_elevation = 90 - theta;
elevation_index = round((cut_elevation + 90) / 2) + 1;

% MATLAB uses azimuth/elevation, whereas the gprMax requests use theta/phi.
% For signed alpha, select the positive- or negative-axis half-plane.
xz_grid = pattern( ...
    antenna, ...
    pattern_frequency, ...
    [0 180], ...
    elevation, ...
    Type="directivity", ...
    Normalize=false ...
);
if size(xz_grid, 1) ~= numel(elevation)
    xz_grid = xz_grid.';
end
xz_column = ones(size(alpha));
xz_column(alpha < 0) = 2;
xz_index = sub2ind(size(xz_grid), elevation_index, xz_column);
xz_directivity_dbi = xz_grid(xz_index);

yz_grid = pattern( ...
    antenna, ...
    pattern_frequency, ...
    [90 -90], ...
    elevation, ...
    Type="directivity", ...
    Normalize=false ...
);
if size(yz_grid, 1) ~= numel(elevation)
    yz_grid = yz_grid.';
end
yz_column = ones(size(alpha));
yz_column(alpha < 0) = 2;
yz_index = sub2ind(size(yz_grid), elevation_index, yz_column);
yz_directivity_dbi = yz_grid(yz_index);

pattern_output = table( ...
    alpha, ...
    theta, ...
    cut_elevation, ...
    xz_directivity_dbi, ...
    yz_directivity_dbi, ...
    VariableNames=[ ...
        "angle_deg", ...
        "theta_deg", ...
        "elevation_deg", ...
        "xz_directivity_dbi", ...
        "yz_directivity_dbi" ...
    ] ...
);
writetable( ...
    pattern_output, ...
    fullfile(results_dir, "dipole_array_matlab_pattern.csv") ...
);

gprmax_ports_path = fullfile(results_dir, "dipole_array_gprmax_active_ports.csv");
if ~isfile(gprmax_ports_path)
    error( ...
        "Run dipole_array_gprmax.py first so the shared frequency grid " + ...
        "is available at %s", ...
        gprmax_ports_path ...
    );
end
gprmax_ports = readtable(gprmax_ports_path);
frequency_stride = 8;
frequency_indices = (1:frequency_stride:height(gprmax_ports)).';
if frequency_indices(end) ~= height(gprmax_ports)
    frequency_indices(end + 1) = height(gprmax_ports);
end
active_frequency = gprmax_ports.frequency_hz(frequency_indices);
active_impedance_by_port = impedance(antenna, active_frequency);
if size(active_impedance_by_port, 1) ~= numel(active_frequency)
    active_impedance_by_port = active_impedance_by_port.';
end
if ~isequal(size(active_impedance_by_port), [numel(active_frequency), 2])
    error("Unexpected two-element active-impedance dimensions.");
end
active_impedance = mean(active_impedance_by_port, 2);
active_gamma = (active_impedance - reference_impedance) ./ ...
    (active_impedance + reference_impedance);

port_1_impedance = active_impedance_by_port(:, 1);
port_2_impedance = active_impedance_by_port(:, 2);
active_output = table( ...
    active_frequency, ...
    real(port_1_impedance), ...
    imag(port_1_impedance), ...
    real(port_2_impedance), ...
    imag(port_2_impedance), ...
    real(active_impedance), ...
    imag(active_impedance), ...
    real(active_gamma), ...
    imag(active_gamma), ...
    20 * log10(abs(active_gamma)), ...
    rad2deg(angle(active_gamma)), ...
    VariableNames=[ ...
        "frequency_hz", ...
        "port_1_active_impedance_real_ohm", ...
        "port_1_active_impedance_imag_ohm", ...
        "port_2_active_impedance_real_ohm", ...
        "port_2_active_impedance_imag_ohm", ...
        "mean_active_impedance_real_ohm", ...
        "mean_active_impedance_imag_ohm", ...
        "active_gamma_real", ...
        "active_gamma_imag", ...
        "active_gamma_magnitude_db", ...
        "active_gamma_phase_deg" ...
    ] ...
);
writetable(active_output, fullfile(results_dir, "dipole_array_matlab_active.csv"));

save( ...
    fullfile(results_dir, "dipole_array_matlab.mat"), ...
    "element_length", ...
    "element_spacing", ...
    "wire_radius", ...
    "pattern_frequency", ...
    "reference_impedance", ...
    "alpha", ...
    "xz_directivity_dbi", ...
    "yz_directivity_dbi", ...
    "active_frequency", ...
    "frequency_stride", ...
    "active_impedance_by_port", ...
    "active_gamma" ...
);

fprintf( ...
    "Saved MATLAB array patterns at %.3f GHz and %d active-port samples to %s\n", ...
    pattern_frequency / 1e9, ...
    numel(active_frequency), ...
    results_dir ...
);
