% MATLAB PO and MoM comparisons for the square- and circular-PEC-plate cases.

clear;
close all;

script_dir = fileparts(mfilename("fullpath"));
results_dir = fullfile(script_dir, "results");
if ~isfolder(results_dir)
    mkdir(results_dir);
end

c0 = physconst("lightspeed");
wavelength = 3.25e-2;
frequency = c0 / wavelength;
square_length = 10.16e-2;
square_width = 10.16e-2;
circle_radius = 10.16e-2;

square_stl = fullfile(results_dir, "square_plate_reference.stl");
circle_stl = fullfile(results_dir, "circular_plate_reference.stl");
write_square_stl(square_stl, square_length, square_width);
write_circle_stl(circle_stl, circle_radius, 256);

targets = ["square", "circle"];
meshes = ["coarse", "fine"];
saved_targets = cell(0, 1);
reference_columns = { ...
    'elevation_deg', ...
    'matlab_po_rcs_dbsm', ...
    'matlab_po_rcs_m2', ...
    'matlab_mom_rcs_dbsm', ...
    'matlab_mom_rcs_m2', ...
    'analytical_po_rcs_dbsm', ...
    'analytical_po_rcs_m2' ...
};
matlab_reference = struct();
for target = targets
    if target == "square"
        stl_path = square_stl;
    else
        stl_path = circle_stl;
    end
    for mesh_name = meshes
        gprmax_path = fullfile( ...
            results_dir, ...
            target + "_" + mesh_name + "_gprmax.csv" ...
        );
        if ~isfile(gprmax_path)
            continue;
        end
        platform_model = platform(FileName=stl_path, Units="m");
        gprmax_data = readtable(gprmax_path, TextType="string");
        elevation = gprmax_data.actual_elevation_deg;
        matlab_po_dbsm = rcs( ...
            platform_model, ...
            frequency, ...
            0, ...
            elevation, ...
            Solver="PO", ...
            Polarization="HH" ...
        );
        matlab_po_dbsm = reshape(matlab_po_dbsm, [], 1);
        if numel(matlab_po_dbsm) ~= numel(elevation)
            error("Unexpected MATLAB RCS output dimensions for %s.", target);
        end
        mesh(platform_model, MaxEdgeLength=wavelength / 10);
        matlab_mom_dbsm = rcs( ...
            platform_model, ...
            frequency, ...
            0, ...
            elevation, ...
            Solver="MoM", ...
            Polarization="HH" ...
        );
        matlab_mom_dbsm = reshape(matlab_mom_dbsm, [], 1);
        if numel(matlab_mom_dbsm) ~= numel(elevation)
            error("Unexpected MATLAB MoM output dimensions for %s.", target);
        end

        if target == "square"
            analytical_po_m2 = analytical_square( ...
                elevation, square_length, square_width, wavelength ...
            );
        else
            analytical_po_m2 = analytical_circle( ...
                elevation, circle_radius, wavelength ...
            );
        end
        analytical_po_dbsm = 10 * log10(max(analytical_po_m2, realmin));
        output = table( ...
            elevation, ...
            matlab_po_dbsm, ...
            10.^(matlab_po_dbsm / 10), ...
            matlab_mom_dbsm, ...
            10.^(matlab_mom_dbsm / 10), ...
            analytical_po_dbsm, ...
            analytical_po_m2, ...
            VariableNames=[ ...
                "elevation_deg", ...
                "matlab_po_rcs_dbsm", ...
                "matlab_po_rcs_m2", ...
                "matlab_mom_rcs_dbsm", ...
                "matlab_mom_rcs_m2", ...
                "analytical_po_rcs_dbsm", ...
                "analytical_po_rcs_m2" ...
            ] ...
        );
        output_path = fullfile( ...
            results_dir, target + "_" + mesh_name + "_matlab.csv" ...
        );
        writetable(output, output_path);
        case_name = target + "_" + mesh_name;
        saved_targets{end + 1, 1} = char(case_name); %#ok<SAGROW>
        matlab_reference.(case_name) = table2array(output);
        fprintf( ...
            "Saved MATLAB PO %s/%s RCS at %d angles to %s\n", ...
            target, mesh_name, numel(elevation), output_path ...
        );
    end
end

save( ...
    fullfile(results_dir, "plate_rcs_matlab.mat"), ...
    "frequency", ...
    "wavelength", ...
    "square_length", ...
    "square_width", ...
    "circle_radius", ...
    "saved_targets", ...
    "reference_columns", ...
    "matlab_reference" ...
);


function write_square_stl(path, length_x, width_y)
    points = [ ...
        -length_x / 2, -width_y / 2, 0; ...
         length_x / 2, -width_y / 2, 0; ...
         length_x / 2,  width_y / 2, 0; ...
        -length_x / 2,  width_y / 2, 0 ...
    ];
    faces = [1 2 3; 1 3 4];
    stlwrite(triangulation(faces, points), path);
end


function write_circle_stl(path, radius, number_of_segments)
    phi = (0:number_of_segments - 1).' * 2 * pi / number_of_segments;
    points = [ ...
        0, 0, 0; ...
        radius * cos(phi), radius * sin(phi), zeros(size(phi)) ...
    ];
    outer = (2:number_of_segments + 1).';
    next = [outer(2:end); outer(1)];
    faces = [ones(number_of_segments, 1), outer, next];
    stlwrite(triangulation(faces, points), path);
end


function sigma = analytical_square(elevation, length_x, width_y, wavelength)
    argument = 2 * pi * length_x .* cosd(elevation) / wavelength;
    aperture = length_x * width_y;
    sigma = 4 * pi * aperture^2 / wavelength^2 .* sind(elevation).^2 .* ...
        sinc(argument / pi).^2;
end


function sigma = analytical_circle(elevation, radius, wavelength)
    argument = 4 * pi * radius .* cosd(elevation) / wavelength;
    airy = ones(size(argument));
    nonzero = abs(argument) > eps;
    airy(nonzero) = 2 * besselj(1, argument(nonzero)) ./ argument(nonzero);
    aperture = pi * radius^2;
    sigma = 4 * pi * aperture^2 / wavelength^2 .* sind(elevation).^2 .* airy.^2;
end
